### ISSUE TITLE
openke这个库在哪里可以安装？

### ISSUE THREAD

**Issue by wuhq1** [yeeeqichen/KGQA#1]

**Comment by yeeeqichen** [comment]
这个库是由清华nlp组开发的，目前已经在github开源，clone地址为git@github.com:thunlp/OpenKE.git，希望对你有帮助！

**Comment by wuhq1** [comment]
感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月9日(周一) 下午3:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yeeeqichen/KGQA] openke这个库在哪里可以安装？ (#1)




 
***@***.***:thunlp/OpenKE.git，希望对你有帮助！
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
