### ISSUE TITLE
运行router出现问题

### ISSUE THREAD

**Issue by justyyau** [yeeeqichen/KGQA#3]
RuntimeError: Error(s) in loading state_dict for QuestionAnswerModel:
	Missing key(s) in state_dict: "relation_predictor.attention_key.weight", "relation_predictor.attention_key.bias", "relation_predictor.attention_query.weight", "relation_predictor.attention_query.bias", "relation_predictor.attention_value.weight", "relation_predictor.attention_value.bias", "relation_predictor.feed_forward.weight", "relation_predictor.feed_forward.bias". 
	Unexpected key(s) in state_dict: "relation_predictor.attention_w.weight", "relation_predictor.attention_w.bias".
按照博主的方式运行train.py，到了下一步运行router.py就出现以上的问题，求助下博主

**Comment by yeeeqichen** [comment]
你好，感谢关注我的工作，经检查是 QA_model 中`attention_method` 赋值错误，已经进行修改
