### ISSUE TITLE
negative_samples

### ISSUE THREAD

**Issue by justyyau** [yeeeqichen/KGQA#4]
博主我不太明白，为什么训练的时候要加入negative_samples呀

**Comment by yeeeqichen** [comment]
你好，因为所使用的损失函数是constrastive loss, 训练的目标不仅是希望模型能够对于正确的三元组给予积极评价，而且要对不正确的三元组（negative_samples)进行区分

**Comment by justyyau** [comment]
嗯嗯，好的，非常感谢博主
