### ISSUE TITLE
请问有没有相关的论文资源可供参考？

### ISSUE THREAD

**Issue by kwl0715** [yeeeqichen/KGQA#5]
请问有相关的论文资源可以参考吗，代码注释比较少，感觉有些难看懂。

**Comment by justyyau** [comment]
可以看看transe什么的

**Comment by yeeeqichen** [comment]
这边整理了一些相关资料

KGQA:
[参考paper1](https://aclanthology.org/2020.acl-main.412/)
[参考paper2](https://aclanthology.org/P17-1021/?ref=https://githubhelp.com)

KG embed:
[TransE](https://proceedings.neurips.cc/paper/2013/file/1cecc7a77928ca8133fa24680a88d2f9-Paper.pdf)
[RotatE](https://arxiv.org/pdf/1902.10197?ref=https://githubhelp.com)

希望对你有所帮助
