### ISSUE TITLE
初始化训练和测试用的五个文件

### ISSUE THREAD

**Issue by LoneChristmas** [yeeeqichen/KGQA#7]
你好，我用kb.txt去初始化训练和测试用的五个文件：然后执行的时候如下：
python3 train_rotate.py
Input Files Path : ./data/MetaQA/
The toolkit is importing datasets.
The total of relations is 9.
The total of entities is  #43234.
The total of train triples is 106066.
Input Files Path : ./data/MetaQA/
The total of test triples is 13258.
The total of valid triples is 13259.
Segmentation fault
我发现kb.txt里面有的三元组是重复的，所以我手动去除了删除了的三元组，然后打乱数据集并按照8:1:1的比例划分为训练集、验证集和测试集，我在entity2id.txt和relation2id.txt用了'\t'分隔，在剩余几个个文件之间用了空格，想请教一下大概会是什么原因导致的"Segmentation fault"?

**Comment by yeeeqichen** [comment]
出现段错误的最大可能原因：embedding越界

可以进行如下检查：
- rotatE方法初始化的item embedding矩阵大小 是否 == entity数量
- rotatE方法初始化的relation embedding 矩阵大小是否 == relation数量

**Comment by LoneChristmas** [comment]
非常感谢您，上面的问题解决了，但是我遇到了一个新问题，就是运行rotate训练的时候直接卡死了，如下：
Finish initializing...
  0%|                                                                                                                              | 0/1500 [00:00<?, ?it/s]
其他模型没什么问题，唯独rotate，想问一下会是我笔记本的gpu性能不够吗（GTX1660ti）？

**Comment by LoneChristmas** [comment]
> 非常感谢您，上面的问题解决了，但是我遇到了一个新问题，就是运行rotate训练的时候直接卡死了，如下： Finish initializing... 0%| | 0/1500 [00:00<?, ?it/s] 其他模型没什么问题，唯独rotate，想问一下会是我笔记本的gpu性能不够吗（GTX1660ti）？

好了，应该是性能问题了，等了好一会他动了：Finish initializing...
Epoch 0 | loss: 8314.016594:   0%|                                                                                    | 1/1500 [07:01<175:26:14, 421.33s/it]，想请教一下作者是用的linux服务器吗，是的话有没有推荐的？

**Comment by yeeeqichen** [comment]
可以考虑租一个入门的云服务器，例如1 ～ 2 卡的2080 ti / V100进行训练，不推荐使用个人电脑哈

这边可以推荐一个平台：https://matpool.com

**Comment by LoneChristmas** [comment]
> 可以考虑租一个入门的云服务器，例如1 ～ 2 卡的2080 ti / V100进行训练，不推荐使用个人电脑哈
> 
> 这边可以推荐一个平台：https://matpool.com

多谢指点！

**Comment by LoneChristmas** [comment]
想问一下作者跑train_rotate.py花费了多少时间，我这里显示总共要66h（batch为10），我想适当增大一下batch让他加快一点(主要是服务器有点贵......)，但这貌似会对训练效果造成影响。

**Comment by kokoro-ele** [comment]
> 非常感谢您，上面的问题解决了，但是我遇到了一个新问题，就是运行rotate训练的时候直接卡死了，如下： Finish initializing... 0%| | 0/1500 [00:00<?, ?it/s] 其他模型没什么问题，唯独rotate，想问一下会是我笔记本的gpu性能不够吗（GTX1660ti）？

您好，请问您的笔记本是windows系统的吗？如果是的话您是如何在windows上把openke跑起来的？

**Comment by LoneChristmas** [comment]
> 

你好，建议使用linux，网上好像没找到在windows成功的案例。你可以用vscode+wsl使用ubuntu，网上有很详细的教程。或者可以搞一个带gpu的linux服务器。

**Comment by LoneChristmas** [comment]
> > 
> 
> 你好，建议使用linux，网上好像没找到在windows成功的案例。你可以用vscode+wsl使用ubuntu，网上有很详细的教程。或者可以搞一个带gpu的linux服务器。

是windos的

**Comment by yeeeqichen** [comment]
> 想问一下作者跑train_rotate.py花费了多少时间，我这里显示总共要66h（batch为10），我想适当增大一下batch让他加快一点(主要是服务器有点贵......)，但这貌似会对训练效果造成影响。

在这个项目中，batch_size 对效果的影响我并没有实际测试过，如果时间确实过长可以考虑增大bsz

**Comment by LoneChristmas** [comment]
> 
好的谢谢！

**Comment by kokoro-ele** [comment]
> 非常感谢您，上面的问题解决了，但是我遇到了一个新问题，就是运行rotate训练的时候直接卡死了，如下： Finish initializing... 0%| | 0/1500 [00:00<?, ?it/s] 其他模型没什么问题，唯独rotate，想问一下会是我笔记本的gpu性能不够吗（GTX1660ti）？

您好，感谢您之前的回复，现在我遇到了跟您一模一样的问题（报错信息也一样），请问您如何解决的？

**Comment by kokoro-ele** [comment]
> 你好，我用kb.txt去初始化训练和测试用的五个文件：然后执行的时候如下： python3 train_rotate.py Input Files Path : ./data/MetaQA/ The toolkit is importing datasets. The total of relations is 9. The total of entities is #43234. The total of train triples is 106066. Input Files Path : ./data/MetaQA/ The total of test triples is 13258. The total of valid triples is 13259. Segmentation fault 我发现kb.txt里面有的三元组是重复的，所以我手动去除了删除了的三元组，然后打乱数据集并按照8:1:1的比例划分为训练集、验证集和测试集，我在entity2id.txt和relation2id.txt用了'\t'分隔，在剩余几个个文件之间用了空格，想请教一下大概会是什么原因导致的"Segmentation fault"?

您好，感谢您之前的回复。我现在也遇到了Segmentation fault问题，报错信息跟您一模一样（除了train triple 我的数量是106865），请问您是如何解决的？（已解决，我把type_constraint改成false可以跑了）
