### ISSUE TITLE
train_loss.backward()中的cuda错误

### ISSUE THREAD

**Issue by LoneChristmas** [yeeeqichen/KGQA#9]
我执行KGQA-SYStem中的train.py的时候显示如下： KG_embed.ent_embeddings.weight : torch.Size([43234, 2048])，KG_embed.rel_embeddings.weight : torch.Size([9, 1024])
他告诉我在执行 File "train.py", line 162, in train的 train_loss.backward()的时候出现了cuda错误：File "/home/stone/miniconda3/envs/python35/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/stone/miniconda3/envs/python35/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA error: unknown error
想请教一下您这是什么问题呢，是我的模型的size对不上还是环境没有配好呢？

**Comment by cliy5** [comment]
你好，请问您最终解决这个问题了吗？

**Comment by cliy5** [comment]
> 我执行KGQA-SYStem中的train.py的时候显示如下： KG_embed.ent_embeddings.weight : torch.Size([43234, 2048])，KG_embed.rel_embeddings.weight : torch.Size([9, 1024]) 他告诉我在执行 File "train.py", line 162, in train的 train_loss.backward()的时候出现了cuda错误：File "/home/stone/miniconda3/envs/python35/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/home/stone/miniconda3/envs/python35/lib/python3.7/site-packages/torch/autograd/**init**.py", line 147, in backward allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag RuntimeError: CUDA error: unknown error 想请教一下您这是什么问题呢，是我的模型的size对不上还是环境没有配好呢？

您好，请问您解决这个问题了吗？执行train.py时，我遇到了相似的错误，RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
